apiVersion: v1
kind: Service
metadata:
  name: {{ include "provisioning_server.fullname" . }}
  labels:
    {{- include "provisioning_server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  externalIPs:
    - {{ .Values.service.externalIP }}
  selector:
    {{- include "provisioning_server.selectorLabels" . | nindent 4 }}
